views/home/__init__.py
# 3rd party imports
from flask import Blueprint


home = Blueprint('home', __name__)

# Local import
import views.home.views as views

views/home/views.py
# third-party imports
from flask import render_template, abort
from flask_login import login_required, current_user
# local imports
from views.home import home


@home.route('/')
def homepage():
    """Render the homepage template on the / route.
    Render homepage, otherwise raise errors.
    Returns:
         home/index.html: homepage html.

    """
    return render_template('home/index.html')


@home.route('/dashboard')
@login_required
def dashboard():
    """Render the dashboard template on the /dashboard route.

    Render dashboard, otherwise raise errors.
    Returns:
        home/dashboard.html: dashboard html.

    """
    return render_template('home/dashboard.html', title="Dashboard")


@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    """Return rendered admin-user page.

    Render admin-user page after checking out admin rights.
    Returns:
        home/admin_dashboard.html: admin dashboard html
    """

    if not current_user.is_admin:
        abort(403)

    return render_template('home/admin_dashboard.html', title='Dashboard')

templates/home/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
{#                    <h1>Admin Dashboard</h1>#}
                    <h1>Admin Dashboard</h1>
                    <h3>For administrators only!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home/dashboard.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %} {% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Hello {{current_user.first_name}}</h1>
                    <h3>Welcome to MyPy web application. Here we go again</h3>
                    </ul>
                    <br>
                    <br>
                    <a href="{{ url_for('home.homepage') }}" id="profilebtn">View your profile</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>PYTHON</h1>
                    <h3>Connecting people!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}